### ISSUE TITLE
How can I set the validity time of the cache 

### ISSUE THREAD

**Issue by a523** [heylouiz/scrapy-s3-http-cache#6]
How can I set the validity time of the cache ？
And  if the cache is not valid，the program can update it auto?

**Comment by heylouiz** [comment]
Hi @a523 
For my usage I use this extension as a time machine.
I store all requests made by a spider so in the future if I want to extract the same data but with minor tweaks, like extracting a new value from the page, I just run the spider again using this cache.

I think this cannot be used as a regular cache backend, like others available in scrapy (db, filesystem)
But to be honest I haven't tested it in different scenarios.

**Comment by a523** [comment]
@heylouiz Thanks for the reply.
Now，I have found a option named ‘HTTPCACHE_EXPIRATION_SECS’ from [scrapy docs](https://docs.scrapy.org/en/latest/topics/downloader-middleware.html#std-setting-HTTPCACHE_EXPIRATION_SECS).  It looked like it would meet my needs. This option should work in this extension, right?

**Comment by a523** [comment]
AND, I have another Idear， even if the ‘HTTPCACHE_EXPIRATION_SECS’ option is not work。I can set the [s3 lifecycle](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html), the cache object can auto delete from s3  after a certain period of time , then  the scrapy extension can get info from the original url, right?
